# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

<<<<<<< Updated upstream
general:
  build_dir: deliverables/D3/unicef-mapbox-plugin

=======
>>>>>>> Stashed changes
orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  #This is the job to check that CircleCI is configured properly.
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo CircleCI properly configured on github!"

  check-env:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Check env"
          command: |
            echo "Checking if environment variables are properly configured"
            stage="STAGE_${NPM_KEY}"
            if [[ -n ${!stage} ]]; then
            echo "Environment variable NPM_KEY is set."
            else
            echo "Envirionment variable NPM_KEY is not set."
            fi

            #This is the job to check that all jest tests have passed.
#NOW REPLACED WITH ORB NODE/TEST in workflow
  # test:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: npm
  #     - run:
  #         name: "Run Tests"
  #         command: npm test
  #     - store_test_results:
  #         path: test-results

  #This is the job to publish to npm.
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=${NPM_KEY}
            npm publish

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  test-and-publish:
    jobs:
      - check_env
      - node/test:
          app-dir: "~/project/deliverables/D3/mapbox-plugin"
          test-results-for: jest
      - publish:
          app-dir: "~/project/deliverables/D3/mapbox-plugin"
          test-results-for: jest
          requires:
            - check_env
            - node/test
