# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  #This is the job to check that CircleCI is configured properly.
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo CircleCI properly configured on github!"

  check-env:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Check env"
          command: |
            if [[ -z "${NPM_KEY}" ]]; then
               echo "environment variable NPM_KEY is set."
            else
              echo "environment variable NPM_KEY is not set."
            fi
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            cd  ./deliverables/D3/mapbox-plugin
            npm set //registry.npmjs.org/:_authToken=${NPM_KEY}
            npm publish

          # Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  test-and-publish:
    jobs:
      - check-env
      - node/test:
          app-dir: "~/project/deliverables/D3/mapbox-plugin"
          test-results-for: jest
      - publish:
          requires:
            - check-env
            - node/test